### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by rgimad** [l4l/kolibri-hello-world#2]
Installed cargo make and nasm (also added to user and system Path)

```
C:\Users\rgimad\Documents\Programming_projects\KOS_STUFF\kolibri-hello-world>cargo make --profile production
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Project: hw_kolibri
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: default
[cargo-make] INFO - Profile: production
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Execute Command: "cargo" "build" "--release"
   Compiling hw_kolibri v0.1.0 (C:\Users\rgimad\Documents\Programming_projects\KOS_STUFF\kolibri-hello-world)
error: failed to run custom build command for `hw_kolibri v0.1.0 (C:\Users\rgimad\Documents\Programming_projects\KOS_STUFF\kolibri-hello-world)`

Caused by:
  process didn't exit successfully: `C:\Users\rgimad\Documents\Programming_projects\KOS_STUFF\kolibri-hello-world\target\release\build\hw_kolibri-621318d8e75ad7da\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=src/syscalls.S
  running: "nasm" "" "-f elf32" "C:\\Users\\rgimad\\Documents\\Programming_projects\\KOS_STUFF\\kolibri-hello-world\\src/syscalls.S" "-o" "C:\\Users\\rgimad\\Documents\\Programming_projects\\KOS_STUFF\\kolibri-hello-world\\target\\i686-kolibri\\release\\build\\hw_kolibri-265dec5121a35c98\\out\\src/syscalls.o"
  running: "lib" "/OUT:C:\\Users\\rgimad\\Documents\\Programming_projects\\KOS_STUFF\\kolibri-hello-world\\target\\i686-kolibri\\release\\build\\hw_kolibri-265dec5121a35c98\\out\\libsyscalls.a" "C:\\Users\\rgimad\\Documents\\Programming_projects\\KOS_STUFF\\kolibri-hello-world\\target\\i686-kolibri\\release\\build\\hw_kolibri-265dec5121a35c98\\out\\src/syscalls.o"

  --- stderr
  thread 'main' panicked at 'failed to compile assembly: "failed to spawn process: program not found"', build.rs:4:10
  stack backtrace:
     0:     0x7ff794199def - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff794199def - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff794199def - std::sys_common::backtrace::_print_fmt
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\sys_common\backtrace.rs:67
     3:     0x7ff794199def - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\sys_common\backtrace.rs:46
     4:     0x7ff7941afcea - core::fmt::write
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\core\src\fmt\mod.rs:1149
     5:     0x7ff794194ea8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\io\mod.rs:1697
     6:     0x7ff79419c3e6 - std::sys_common::backtrace::_print
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\sys_common\backtrace.rs:49
     7:     0x7ff79419c3e6 - std::sys_common::backtrace::print
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\sys_common\backtrace.rs:36
     8:     0x7ff79419c3e6 - std::panicking::default_hook::closure$1
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:211
     9:     0x7ff79419becc - std::panicking::default_hook
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:228
    10:     0x7ff79419ca45 - std::panicking::rust_panic_with_hook
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:606
    11:     0x7ff79419c62b - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:502
    12:     0x7ff79419a717 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\sys_common\backtrace.rs:139
    13:     0x7ff79419c589 - std::panicking::begin_panic_handler
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:498
    14:     0x7ff7941b4f40 - core::panicking::panic_fmt
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\core\src\panicking.rs:107
    15:     0x7ff7941b4fe3 - core::result::unwrap_failed
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\core\src\result.rs:1660
    16:     0x7ff794171122 - core::result::Result<T,E>::expect::h8ab19e0abedaa949
    17:     0x7ff7941711e4 - core::result::Result<T,E>::expect::h8ab19e0abedaa949
    18:     0x7ff794171376 - core::ops::function::FnOnce::call_once::h6970223fd70e0477
    19:     0x7ff794171067 - std::sys_common::backtrace::__rust_begin_short_backtrace::h393095b75ae5a355
    20:     0x7ff79417103c - std::rt::lang_start::{{closure}}::h1df5f8eb1b5d9206
    21:     0x7ff794199737 - core::ops::function::impls::impl$2::call_once
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\library\core\src\ops\function.rs:259
    22:     0x7ff794199737 - std::panicking::try::do_call
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:406
    23:     0x7ff794199737 - std::panicking::try
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:370
    24:     0x7ff794199737 - std::panic::catch_unwind
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panic.rs:133
    25:     0x7ff794199737 - std::rt::lang_start_internal::closure$2
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\rt.rs:128
    26:     0x7ff794199737 - std::panicking::try::do_call
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:406
    27:     0x7ff794199737 - std::panicking::try
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panicking.rs:370
    28:     0x7ff794199737 - std::panic::catch_unwind
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\panic.rs:133
    29:     0x7ff794199737 - std::rt::lang_start_internal
                                 at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38\/library\std\src\rt.rs:128
    30:     0x7ff794171020 - std::rt::lang_start::h48a342896efd0b35
    31:     0x7ff794171206 - main
    32:     0x7ff7941b39e4 - invoke_main
                                 at d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    33:     0x7ff7941b39e4 - __scrt_common_main_seh
                                 at d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    34:     0x7ff9af927034 - BaseThreadInitThunk
    35:     0x7ff9b17e2651 - RtlUserThreadStart
[cargo-make] ERROR - Error while executing command, exit code: 101
[cargo-make] WARN - Build Failed.

C:\Users\rgimad\Documents\Programming_projects\KOS_STUFF\kolibri-hello-world>
```

**Comment by l4l** [comment]
Are you sure `nasm` binary is usable at your env?

**Comment by rgimad** [comment]
Yes, when I type ```nasm``` in terminals it runs ok. I think maybe problem in nasm-rs (idk does it support windows or not) Btw did you test build on windows ?
